yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.fields.related import ForeignKey

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('URL', unique=True)
    description = models.TextField('Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы авторов'
        ordering = ('title',)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Текст нового поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        related_name='group_posts',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты авторов'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        'Комментарий',
        help_text='Комментарий к посту'
    )
    created = models.DateTimeField('Дата комментария', auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Ссылка на пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Ссылка на автора комментария'
    )

    class Meta:
        verbose_name = 'Комментарий автора'
        verbose_name_plural = 'Комментарии авторов'
        ordering = ('-created',)

    def __str__(self) -> str:
        return (
            f'Комментарий "{self.text[:10]}"'
            f' к посту номер {self.post.id}'
        )


class Follow(models.Model):
    user = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
        help_text='Пользователь, который подписывается',
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор, на которого подписывается пользователь',
    )

    class Meta:
        verbose_name = 'Подписка на автора'
        verbose_name_plural = 'Подписки на авторов'

    def __str__(self) -> str:
        return (
            f'Пользователь {self.user.username}'
            f' подписан на автора {self.author.username}'
        )

yatube/posts/forms.py
from django import forms

from .models import Comment, Group, Post


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea,
        label='Текст поста',
        help_text='Введите новый текст или отредактируйте существующий'
    )
    group = forms.ModelChoiceField(
        label='Группа, в которую входит пост',
        help_text='Выберите или измените группу, в которую входит пост',
        required=False,
        queryset=Group.objects.all()
    )
    image = forms.ImageField(
        label='Здесь загружаем картинки к постам',
        help_text='Выберите файл картинки.'
                  ' Для замены ранее загруженного файла сначала'
                  ' поставьте галочку "Очистить" и нажмите сохранить.',
        required=False
    )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings as s
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, s.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.group_posts.all()
    paginator = Paginator(post_list, s.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    following: bool = False
    # Берем автора профайла
    author = get_object_or_404(User, username=username)
    # Берем список подписавшихся пользователей автора,
    subscriptions = author.following.all()
    # Проверяем, содержат ли подписки автора
    # пользователя, который просматривает его профайл
    for subscription in subscriptions:
        if subscription.user == request.user:
            following = True
    # Формируем вывод список постов автора с разбивкой на страницы
    posts_list = Post.objects.filter(author=author)
    paginator = Paginator(posts_list, s.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()

    context = {
        'post': post,
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        user = request.user
        form_instance_with_author = form.save(commit=False)
        form_instance_with_author.author = user
        form_instance_with_author.save()
        return redirect('posts:profile', username=user.username)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit: bool = False
    user = request.user
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None)
    if post.author == user:
        if request.method == 'POST' and form.is_valid():
            post.text = form.cleaned_data['text']
            post.image = form.cleaned_data['image']
            post.save()
            return redirect('posts:post_detail', post_id=post.id)
        form = PostForm(instance=post)
        is_edit: bool = True
        context = {
            'form': form,
            'is_edit': is_edit,
            'post_id': post_id,
        }
        return render(request, template, context)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    # Берем список подписок нашего пользователя
    subscriptions = Follow.objects.filter(user=request.user)
    posts_list = list()
    # Из списка подписок берём каждую подписку
    for subscription in subscriptions:
        # В каждой подписке берём автора, на которого подписан пользователь
        # у автора берем все его посты
        # для того, чтобы список постов был итерируемым добавляем метод all()
        for post in subscription.author.posts.all():
            posts_list.append(post)
    # Добавляем разбивку на страницы
    paginator = Paginator(posts_list, s.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    template = 'posts/became_follow.html'
    user = get_object_or_404(User, username=request.user.username)
    author = get_object_or_404(User, username=username)
    # Проверяем, что пользователь еще не подписан на автора
    if request.user.username != username:
        user_already_subscribed = False
        # Берем у автора все подписки  пользователей
        subscriptions = author.following.all()
        # Проверяем, есть ли в этих подписках наш пользователь
        # просматривающий его профайл
        for subscription in subscriptions:
            if subscription.user == request.user:
                user_already_subscribed = True
        # Если пользователя среди текущих подписок автора не нашли,
        # то создаем подписку
        if not user_already_subscribed:
            Follow.objects.create(user=user, author=author)

    context = {
        'author': author,
    }
    return render(request, template, context)


@login_required
def profile_unfollow(request, username):
    template = 'posts/unfollow.html'
    user = get_object_or_404(User, username=request.user.username)
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=user, author=author).delete()
    context = {
        'author': author,
    }
    return render(request, template, context)

yatube/templates/posts/became_follow.html
<!-- posts/became_follow.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Успешная подписка{{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Вы успешно подписаны на автора {{author.get_full_name}}</h1>
  </div>  
{% endblock %} 

yatube/templates/posts/create_post.html
<!-- posts/create_post.html -->
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">  
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}     
          </div>
          <div class="card-body">      
            {% if is_edit %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
            {% endif %}  
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>    
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!-- posts/follow.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Посты моих авторов{% endblock %}
{% block content %}
  <div class="container py-1">
    <h1>Последние обновления постов моих авторов</h1>
      {% include "includes/switcher.html" %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты автора</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          </ul>
          {% thumbnail post.image "1200x500" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          {% else %}
            <p><span style="color:blue">данный пост не входит ни в одну из существующих групп</span></p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include "includes/paginator.html" %}
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
<!-- posts/group_list.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-1">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "1200x500" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
      {% else %}
        <p><span style="color:blue">данный пост не входит ни в одну из существующих групп</span></p>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include "includes/paginator.html" %}
  </div>  
{% endblock %}

yatube/templates/posts/index.html
<!-- posts/index.html -->
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-1">
    <h1>Последние обновления на сайте</h1>
      {% include "includes/switcher.html" %}
      {% load cache %}
      {% cache 20 index_page %}
      {% include "includes/print_posts.html" %}
      {% include "includes/paginator.html" %}
      {% endcache %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
<!-- posts/post_detail.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% else %}
          <p><span style="color:blue">данный пост не входит ни в одну из существующих групп</span></p>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if  post.author.username == request.user.username %}
        <a href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
      {% include "includes/add_comment.html" %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
<!-- posts/profile.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">  
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ author.posts.count }}</h3>
      {% if user.is_authenticated and user.username != author.username%}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        {% thumbnail post.image "1200x500" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article> 
        {% if post.group %}      
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% else %}
          <p><span style="color:blue">данный пост не входит ни в одну из существующих групп</span></p>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}     
      {% include "includes/paginator.html" %}
    </div>
  </div>  
{% endblock %} 

yatube/templates/posts/unfollow.html
<!-- posts/follow.html -->
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Успешная отписка{{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Вы успешно отписаны от автора {{author.get_full_name}}</h1>
  </div>  
{% endblock %} 